{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "9f0ffb4e-b590-4bff-9b04-868b01ba91a4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pandas in .\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages (3.0.2)\n",
      "Requirement already satisfied: numpy in .\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages (2.4.4)\n",
      "Requirement already satisfied: matplotlib in .\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages (3.10.3)\n",
      "Requirement already satisfied: seaborn in .\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages (0.13.2)\n",
      "Requirement already satisfied: plotly in .\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages (6.8.0)\n",
      "Requirement already satisfied: sqlalchemy in .\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages (2.0.41)\n",
      "Requirement already satisfied: requests in .\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages (2.33.1)\n",
      "Requirement already satisfied: scipy in .\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages (1.16.0)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in .\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages (from pandas) (2.9.0.post0)\n",
      "Requirement already satisfied: tzdata in .\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages (from pandas) (2026.2)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in .\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages (from matplotlib) (1.3.2)\n",
      "Requirement already satisfied: cycler>=0.10 in .\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages (from matplotlib) (0.12.1)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in .\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages (from matplotlib) (4.58.5)\n",
      "Requirement already satisfied: kiwisolver>=1.3.1 in .\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages (from matplotlib) (1.4.8)\n",
      "Requirement already satisfied: packaging>=20.0 in .\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages (from matplotlib) (26.2)\n",
      "Requirement already satisfied: pillow>=8 in .\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages (from matplotlib) (12.2.0)\n",
      "Requirement already satisfied: pyparsing>=2.3.1 in .\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages (from matplotlib) (3.2.3)\n",
      "Requirement already satisfied: narwhals>=1.15.1 in .\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages (from plotly) (2.21.0)\n",
      "Requirement already satisfied: greenlet>=1 in .\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages (from sqlalchemy) (3.2.3)\n",
      "Requirement already satisfied: typing-extensions>=4.6.0 in .\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages (from sqlalchemy) (4.15.0)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in .\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages (from requests) (3.4.7)\n",
      "Requirement already satisfied: idna<4,>=2.5 in .\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages (from requests) (3.14)\n",
      "Requirement already satisfied: urllib3<3,>=1.26 in .\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages (from requests) (2.7.0)\n",
      "Requirement already satisfied: certifi>=2023.5.7 in .\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages (from requests) (2026.4.22)\n",
      "Requirement already satisfied: six>=1.5 in .\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "[notice] A new release of pip is available: 26.1.1 -> 26.1.2\n",
      "[notice] To update, run: python.exe -m pip install --upgrade pip\n"
     ]
    }
   ],
   "source": [
    "pip install pandas numpy matplotlib seaborn plotly sqlalchemy requests scipy"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "00e68ed4-be83-45e4-987b-8eab26834d6f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "Dataset: 01_fund_master.csv\n",
      "\n",
      "Shape: (40, 15)\n",
      "\n",
      "Data types: amfi_code               int64\n",
      "fund_house                str\n",
      "scheme_name               str\n",
      "category                  str\n",
      "sub_category              str\n",
      "plan                      str\n",
      "launch_date               str\n",
      "benchmark                 str\n",
      "expense_ratio_pct     float64\n",
      "exit_load_pct         float64\n",
      "min_sip_amount          int64\n",
      "min_lumpsum_amount      int64\n",
      "fund_manager              str\n",
      "risk_category             str\n",
      "sebi_category_code        str\n",
      "dtype: object\n",
      "\n",
      "First five elements:    amfi_code       fund_house                                   scheme_name  \\\n",
      "0     119551  SBI Mutual Fund     SBI Bluechip Fund - Regular Plan - Growth   \n",
      "1     119552  SBI Mutual Fund      SBI Bluechip Fund - Direct Plan - Growth   \n",
      "2     119598  SBI Mutual Fund    SBI Small Cap Fund - Regular Plan - Growth   \n",
      "3     119599  SBI Mutual Fund     SBI Small Cap Fund - Direct Plan - Growth   \n",
      "4     119120  SBI Mutual Fund  SBI Magnum Gilt Fund - Regular Plan - Growth   \n",
      "\n",
      "  category sub_category     plan launch_date                  benchmark  \\\n",
      "0   Equity    Large Cap  Regular  2006-02-14              NIFTY 100 TRI   \n",
      "1   Equity    Large Cap   Direct  2013-01-01              NIFTY 100 TRI   \n",
      "2   Equity    Small Cap  Regular  2009-09-09       BSE 250 SmallCap TRI   \n",
      "3   Equity    Small Cap   Direct  2013-01-01       BSE 250 SmallCap TRI   \n",
      "4     Debt         Gilt  Regular  2000-12-30  CRISIL Dynamic Gilt Index   \n",
      "\n",
      "   expense_ratio_pct  exit_load_pct  min_sip_amount  min_lumpsum_amount  \\\n",
      "0               1.54            1.0             500                1000   \n",
      "1               0.66            1.0             500                1000   \n",
      "2               1.43            1.0             500                1000   \n",
      "3               0.72            1.0             500                1000   \n",
      "4               0.77            0.0             500                1000   \n",
      "\n",
      "    fund_manager risk_category sebi_category_code  \n",
      "0  Sohini Andani      Moderate               EC01  \n",
      "1  Sohini Andani      Moderate               EC01  \n",
      "2  R. Srinivasan     Very High               EC03  \n",
      "3  R. Srinivasan     Very High               EC03  \n",
      "4   Dinesh Ahuja           Low               DC02  \n",
      "\n",
      "\n",
      "Dataset: 02_nav_history.csv\n",
      "\n",
      "Shape: (46000, 3)\n",
      "\n",
      "Data types: amfi_code      int64\n",
      "date             str\n",
      "nav          float64\n",
      "dtype: object\n",
      "\n",
      "First five elements:    amfi_code        date      nav\n",
      "0     119551  2022-01-03  54.3856\n",
      "1     119551  2022-01-04  54.3474\n",
      "2     119551  2022-01-05  54.6869\n",
      "3     119551  2022-01-06  55.4550\n",
      "4     119551  2022-01-07  55.3692\n",
      "\n",
      "\n",
      "Dataset: 03_aum_by_fund_house.csv\n",
      "\n",
      "Shape: (90, 5)\n",
      "\n",
      "Data types: date                  str\n",
      "fund_house            str\n",
      "aum_lakh_crore    float64\n",
      "aum_crore           int64\n",
      "num_schemes         int64\n",
      "dtype: object\n",
      "\n",
      "First five elements:          date           fund_house  aum_lakh_crore  aum_crore  num_schemes\n",
      "0  2022-03-31      SBI Mutual Fund            6.05     605000          186\n",
      "1  2022-03-31  ICICI Prudential MF            4.65     465000          216\n",
      "2  2022-03-31     HDFC Mutual Fund            4.35     435000          195\n",
      "3  2022-03-31      Nippon India MF            2.70     270000          177\n",
      "4  2022-03-31    Kotak Mahindra MF            2.70     270000          168\n",
      "\n",
      "\n",
      "Dataset: 04_monthly_sip_inflows.csv\n",
      "\n",
      "Shape: (48, 6)\n",
      "\n",
      "Data types: month                            str\n",
      "sip_inflow_crore               int64\n",
      "active_sip_accounts_crore    float64\n",
      "new_sip_accounts_lakh        float64\n",
      "sip_aum_lakh_crore           float64\n",
      "yoy_growth_pct               float64\n",
      "dtype: object\n",
      "\n",
      "First five elements:      month  sip_inflow_crore  active_sip_accounts_crore  \\\n",
      "0  2022-01             11517                       4.91   \n",
      "1  2022-02             11438                       4.93   \n",
      "2  2022-03             12328                       5.09   \n",
      "3  2022-04             11863                       5.48   \n",
      "4  2022-05             12286                       5.55   \n",
      "\n",
      "   new_sip_accounts_lakh  sip_aum_lakh_crore  yoy_growth_pct  \n",
      "0                   9.10                4.80             NaN  \n",
      "1                   8.20                4.85             NaN  \n",
      "2                  10.50                5.01             NaN  \n",
      "3                   9.52                5.12             NaN  \n",
      "4                   8.10                5.15             NaN  \n",
      "\n",
      "\n",
      "Dataset: 05_category_inflows.csv\n",
      "\n",
      "Shape: (144, 3)\n",
      "\n",
      "Data types: month                   str\n",
      "category                str\n",
      "net_inflow_crore    float64\n",
      "dtype: object\n",
      "\n",
      "First five elements:      month         category  net_inflow_crore\n",
      "0  2024-04        Large Cap            2413.0\n",
      "1  2024-04          Mid Cap            3897.0\n",
      "2  2024-04        Small Cap            3533.0\n",
      "3  2024-04        Flexi Cap            4947.0\n",
      "4  2024-04  Large & Mid Cap            4214.0\n",
      "\n",
      "\n",
      "Dataset: 06_industry_folio_count.csv\n",
      "\n",
      "Shape: (21, 6)\n",
      "\n",
      "Data types: month                      str\n",
      "total_folios_crore     float64\n",
      "equity_folios_crore    float64\n",
      "debt_folios_crore      float64\n",
      "hybrid_folios_crore    float64\n",
      "others_folios_crore    float64\n",
      "dtype: object\n",
      "\n",
      "First five elements:      month  total_folios_crore  equity_folios_crore  debt_folios_crore  \\\n",
      "0  2022-01               13.26                 9.28               1.86   \n",
      "1  2022-04               13.91                 9.74               1.95   \n",
      "2  2022-07               13.85                 9.69               1.94   \n",
      "3  2022-10               14.12                 9.88               1.98   \n",
      "4  2023-01               14.81                10.37               2.07   \n",
      "\n",
      "   hybrid_folios_crore  others_folios_crore  \n",
      "0                 0.80                 1.33  \n",
      "1                 0.83                 1.39  \n",
      "2                 0.83                 1.38  \n",
      "3                 0.85                 1.41  \n",
      "4                 0.89                 1.48  \n",
      "\n",
      "\n",
      "Dataset: 07_scheme_performance.csv\n",
      "\n",
      "Shape: (40, 19)\n",
      "\n",
      "Data types: amfi_code               int64\n",
      "scheme_name               str\n",
      "fund_house                str\n",
      "category                  str\n",
      "plan                      str\n",
      "return_1yr_pct        float64\n",
      "return_3yr_pct        float64\n",
      "return_5yr_pct        float64\n",
      "benchmark_3yr_pct     float64\n",
      "alpha                 float64\n",
      "beta                  float64\n",
      "sharpe_ratio          float64\n",
      "sortino_ratio         float64\n",
      "std_dev_ann_pct       float64\n",
      "max_drawdown_pct      float64\n",
      "aum_crore               int64\n",
      "expense_ratio_pct     float64\n",
      "morningstar_rating      int64\n",
      "risk_grade                str\n",
      "dtype: object\n",
      "\n",
      "First five elements:    amfi_code                                   scheme_name       fund_house  \\\n",
      "0     119551     SBI Bluechip Fund - Regular Plan - Growth  SBI Mutual Fund   \n",
      "1     119552      SBI Bluechip Fund - Direct Plan - Growth  SBI Mutual Fund   \n",
      "2     119598    SBI Small Cap Fund - Regular Plan - Growth  SBI Mutual Fund   \n",
      "3     119599     SBI Small Cap Fund - Direct Plan - Growth  SBI Mutual Fund   \n",
      "4     119120  SBI Magnum Gilt Fund - Regular Plan - Growth  SBI Mutual Fund   \n",
      "\n",
      "    category     plan  return_1yr_pct  return_3yr_pct  return_5yr_pct  \\\n",
      "0  Large Cap  Regular           12.42           12.36           14.45   \n",
      "1  Large Cap   Direct           15.25           11.30           14.23   \n",
      "2  Small Cap  Regular           24.56           23.39           20.67   \n",
      "3  Small Cap   Direct           20.59           23.14           21.82   \n",
      "4       Gilt  Regular            5.34            6.07            5.43   \n",
      "\n",
      "   benchmark_3yr_pct  alpha  beta  sharpe_ratio  sortino_ratio  \\\n",
      "0              11.49   0.87  0.89          0.88           1.29   \n",
      "1               9.52   1.78  0.87          0.81           1.29   \n",
      "2              22.16   1.23  0.89          0.94           1.35   \n",
      "3              22.01   1.13  1.04          0.93           1.67   \n",
      "4               4.47   1.60  0.22          1.52           2.11   \n",
      "\n",
      "   std_dev_ann_pct  max_drawdown_pct  aum_crore  expense_ratio_pct  \\\n",
      "0             14.0            -21.70      14288               1.54   \n",
      "1             14.0            -24.43       1231               0.66   \n",
      "2             25.0            -13.35      19259               1.43   \n",
      "3             25.0            -24.78      36061               0.72   \n",
      "4              4.0             -2.30      24101               0.77   \n",
      "\n",
      "   morningstar_rating risk_grade  \n",
      "0                   4   Moderate  \n",
      "1                   3   Moderate  \n",
      "2                   5  Very High  \n",
      "3                   4  Very High  \n",
      "4                   5        Low  \n",
      "\n",
      "\n",
      "Dataset: 08_investor_transactions.csv\n",
      "\n",
      "Shape: (32778, 13)\n",
      "\n",
      "Data types: investor_id               str\n",
      "transaction_date          str\n",
      "amfi_code               int64\n",
      "transaction_type          str\n",
      "amount_inr              int64\n",
      "state                     str\n",
      "city                      str\n",
      "city_tier                 str\n",
      "age_group                 str\n",
      "gender                    str\n",
      "annual_income_lakh    float64\n",
      "payment_mode              str\n",
      "kyc_status                str\n",
      "dtype: object\n",
      "\n",
      "First five elements:   investor_id transaction_date  amfi_code transaction_type  amount_inr  \\\n",
      "0   INV003054       2024-01-01     119092              SIP        1834   \n",
      "1   INV002952       2024-01-01     148567       Redemption      392882   \n",
      "2   INV003420       2024-01-01     118636              SIP         912   \n",
      "3   INV003436       2024-01-01     118634              SIP        1102   \n",
      "4   INV004691       2024-01-01     119094          Lumpsum        8682   \n",
      "\n",
      "         state       city city_tier age_group  gender  annual_income_lakh  \\\n",
      "0    Telangana  Hyderabad       T30       56+  Female                77.1   \n",
      "1       Punjab   Amritsar       B30     18-25    Male                 7.1   \n",
      "2      Haryana  Faridabad       B30     36-45    Male                47.2   \n",
      "3  Maharashtra     Mumbai       T30     36-45  Female                54.4   \n",
      "4        Delhi      Noida       T30     26-35    Male                14.5   \n",
      "\n",
      "  payment_mode kyc_status  \n",
      "0          UPI   Verified  \n",
      "1       Cheque   Verified  \n",
      "2      Mandate   Verified  \n",
      "3       Cheque    Pending  \n",
      "4  Net Banking    Pending  \n",
      "\n",
      "\n",
      "Dataset: 09_portfolio_holdings.csv\n",
      "\n",
      "Shape: (322, 8)\n",
      "\n",
      "Data types: amfi_code              int64\n",
      "stock_symbol             str\n",
      "stock_name               str\n",
      "sector                   str\n",
      "weight_pct           float64\n",
      "market_value_cr      float64\n",
      "current_price_inr    float64\n",
      "portfolio_date           str\n",
      "dtype: object\n",
      "\n",
      "First five elements:    amfi_code stock_symbol                stock_name       sector  weight_pct  \\\n",
      "0     119551    POWERGRID    Power Grid Corporation    Utilities       13.85   \n",
      "1     119551     HDFCBANK             HDFC Bank Ltd      Banking       11.19   \n",
      "2     119551       GRASIM     Grasim Industries Ltd  Diversified        9.90   \n",
      "3     119551      DRREDDY  Dr. Reddy's Laboratories       Pharma        4.76   \n",
      "4     119551   ASIANPAINT          Asian Paints Ltd       Paints       10.25   \n",
      "\n",
      "   market_value_cr  current_price_inr portfolio_date  \n",
      "0           737.09            6011.08     2025-12-31  \n",
      "1            88.97            1074.65     2025-12-31  \n",
      "2           208.45            5964.59     2025-12-31  \n",
      "3           161.32            3748.82     2025-12-31  \n",
      "4           725.90            1321.45     2025-12-31  \n",
      "\n",
      "\n",
      "Dataset: 10_benchmark_indices.csv\n",
      "\n",
      "Shape: (8050, 3)\n",
      "\n",
      "Data types: date               str\n",
      "index_name         str\n",
      "close_value    float64\n",
      "dtype: object\n",
      "\n",
      "First five elements:          date index_name  close_value\n",
      "0  2022-01-03    NIFTY50     17492.79\n",
      "1  2022-01-04    NIFTY50     17689.64\n",
      "2  2022-01-05    NIFTY50     17835.05\n",
      "3  2022-01-06    NIFTY50     17878.51\n",
      "4  2022-01-07    NIFTY50     17759.15\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import os\n",
    "\n",
    "path = r\"E:\\Project\\data\\raw\"\n",
    "\n",
    "files = [f for f in os.listdir(path) if f.endswith(\".csv\")]\n",
    "\n",
    "for file in files:\n",
    "    \n",
    "    print(\"\\n\\nDataset:\", file)\n",
    "\n",
    "    df = pd.read_csv(os.path.join(path,file))\n",
    "\n",
    "    print(\"\\nShape:\", df.shape)\n",
    "    print(\"\\nData types:\",df.dtypes)\n",
    "    print(\"\\nFirst five elements:\",df.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "e3b45d0a-5daf-4ed3-80f3-d59edb0986c6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.DataFrame'>\n",
      "RangeIndex: 8050 entries, 0 to 8049\n",
      "Data columns (total 3 columns):\n",
      " #   Column       Non-Null Count  Dtype  \n",
      "---  ------       --------------  -----  \n",
      " 0   date         8050 non-null   str    \n",
      " 1   index_name   8050 non-null   str    \n",
      " 2   close_value  8050 non-null   float64\n",
      "dtypes: float64(1), str(2)\n",
      "memory usage: 350.5 KB\n"
     ]
    }
   ],
   "source": [
    "df.info()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "3930be55-25f2-4495-8473-ecee6fb36e60",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "np.int64(0)"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.duplicated().sum()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "52d4c6d5-e067-4308-8ae0-e971e644e055",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "date           0\n",
       "index_name     0\n",
       "close_value    0\n",
       "dtype: int64"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.isnull().sum()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1be5a6a3-8f15-4229-a0a2-f2dfae2864d8",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
